provision:
	uv run pyinfra inventories.py provision.py

deploy:
	uv run pyinfra inventories.py deploy.py

health:
	uv run pyinfra inventories.py health.py

provision-dry:
	uv run pyinfra inventories.py provision.py --dry

deploy-dry:
	uv run pyinfra inventories.py deploy.py --dry
